"""
Django settings for Django project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pl*03!w@tqi4kqq&sj5ij^1t8%uy$#mwb%+*9(ce$k9big69f)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_QUICK = True
SIMPLEUI_HOME_ACTION = True
SIMPLEUI_ANALYSIS = True
#SIMPLEUI_HOME_TITLE = '百度一下你就知道' # 【首页】按钮文案配置
#SIMPLEUI_HOME_PAGE = 'http://philippehong.com/' # 可用于嵌入其他链接，这里可以直接方便的嵌入报表链接
#SIMPLEUI_HOME_ICON = 'el el-icon-platform-eleme'
# ICON 支持element-ui和fontawesome  eg：fa fa-user

# 图标ICON 样式查看
#https://element.eleme.cn/#/zh-CN/component/icon
#http://www.fontawesome.com.cn/cheatsheet/
# 经过实际测试，饿了么的图标稍微有点小，而且数量少
SIMPLEUI_CONFIG = {
    'system_keep': True, # 关闭系统菜单
    'menu_display': ['人脸考勤', '人脸数据管理', '考勤记录管理', '登录账户管理'],
    'dynamic': True,    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [{
        'app': 'myapp',
        'name': '人脸考勤',
        'icon': 'fa fa-id-card',
        'models': [{
            'name': '人脸考勤(低风险区)',
            'icon': 'fa fa-plus-square',
            'url': 'myapp/job_detail/'
        }, {
            'name': '人脸考勤(高风险区)',
            'icon': 'fa fa-ambulance',
            'url': 'myapp/job_detail/'
        }, {
            'name': '人脸口罩识别',
            'icon': 'fa fa-stop-circle',
            'url': 'myapp/job_detail/'
        }]
    },{
        'app': 'auth',
        'name': '人脸数据管理',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '增加人脸数据',
            'icon': 'fa fa-copy',
            'url': 'auth/user/'
        }, {
            'name': '删除人脸数据',
            'icon': 'fa fa-eraser',
            'url': 'auth/user/'
        }, {
            'name': '查找人脸数据',
            'icon': 'fa fa-random',
            'url': 'auth/user/'
        }, {
            'name': '修改人脸数据',
            'icon': 'fa fa-step-backward',
            'url': 'auth/user/'
        }]
    }, {
        'name': '考勤记录管理',
        'icon': 'fa fa-history',
        'models': [{
            'name': '考勤记录导出',
            'url': 'http://baidu.com',
            'icon': 'fa fa-save'
        }, {
            'name': '考勤记录补登',
            'url': 'http://baidu.com',
            'icon': 'fa fa-undo'
        }, {
            'name': '考勤记录删除',
            'url': 'http://baidu.com',
            'icon': 'fa fa-eraser'
        }, {
            'name': '考勤记录查找',
            'url': 'http://baidu.com',
            'icon': 'fa fa-random'
        }, {
            'name': '考勤记录修改',
            'url': 'http://baidu.com',
            'icon': 'fa fa-step-backward'
        }]
    }, {
        'name': '登录账户管理',
        'icon': 'fa fa-history',
        'url': 'auth/user/'
    }]
}

SIMPLEUI_ICON = {
    '系统管理': 'fab fa-apple',
    '员工管理': 'fas fa-user-tie'
}

# 广州大学的图标
SIMPLEUI_LOGO = 'https://riyugo.com/i/2021/04/23/itlwkx.png'

SIMPLEUI_STATIC_OFFLINE = True
# 设置上传目录
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# 设置前缀
MEDIA_URL = '/media/'
